### ISSUE TITLE
Parameterize additional fields of submission upload

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/clinvar-api#1]
Fields should be configurable:
- [x] submission name
- [ ] assertion method
- [ ] assertion citation (other options for this field?)
- [x] record status
- [ ] release status
- [ ] number of individuals

**Comment by larrybabb** [comment]
@theferrit32 Can you provide a current status on this? Some additional information on the plan or priority would be super helpful.

**Comment by theferrit32** [comment]
@larrybabb I think this is low priority unless we have a reason to move it higher or just want to knock it out. I think this is only useful in so far as it serves making another submission to clinvar, not on its own. If another submission comes up maybe that'd be a good time to put some effort into improving this codebase.

**Comment by larrybabb** [comment]
We will revive if and when someone requests this.
